spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/test
    username: root
    password: admin
  mail:
    host: smtp.163.com
    username: cha0stech@163.com
    password: OUAVKGFBSAVVFMPU
    port: 465
    properties:
      from: cha0stech@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 0
      host: localhost
      port: 6379

